// SPDX-FileCopyrightText: AnmiTaliDev <anmitalidev@nuros.org>
// SPDX-License-Identifier: GPL-3.0-or-later

#include "aliases.h"

const std::unordered_map<std::string, std::string>& get_timezone_aliases() {
    static const std::unordered_map<std::string, std::string> aliases = {
        {"мск", "Europe/Moscow"},
        {"москва", "Europe/Moscow"},
        {"питер", "Europe/Moscow"},
        {"спб", "Europe/Moscow"},
        {"калининград", "Europe/Kaliningrad"},
        {"самара", "Europe/Samara"},
        {"екатеринбург", "Asia/Yekaterinburg"},
        {"екб", "Asia/Yekaterinburg"},
        {"омск", "Asia/Omsk"},
        {"новосибирск", "Asia/Novosibirsk"},
        {"нск", "Asia/Novosibirsk"},
        {"сибирь", "Asia/Novosibirsk"},
        {"красноярск", "Asia/Krasnoyarsk"},
        {"иркутск", "Asia/Irkutsk"},
        {"якутск", "Asia/Yakutsk"},
        {"владивосток", "Asia/Vladivostok"},
        {"магадан", "Asia/Magadan"},
        {"камчатка", "Asia/Kamchatka"},
        {"киев", "Europe/Kiev"},
        {"украина", "Europe/Kiev"},
        {"минск", "Europe/Minsk"},
        {"беларусь", "Europe/Minsk"},
        {"тбилиси", "Asia/Tbilisi"},
        {"грузия", "Asia/Tbilisi"},
        {"ереван", "Asia/Yerevan"},
        {"армения", "Asia/Yerevan"},
        {"баку", "Asia/Baku"},
        {"азербайджан", "Asia/Baku"},
        {"ташкент", "Asia/Tashkent"},
        {"узбекистан", "Asia/Tashkent"},
        {"самарканд", "Asia/Samarkand"},
        {"нукус", "Asia/Samarkand"},
        {"бишкек", "Asia/Bishkek"},
        {"кыргызстан", "Asia/Bishkek"},
        {"душанбе", "Asia/Dushanbe"},
        {"таджикистан", "Asia/Dushanbe"},
        {"ашхабад", "Asia/Ashgabat"},
        {"туркменистан", "Asia/Ashgabat"},
        {"астана", "Asia/Almaty"},
        {"алматы", "Asia/Almaty"},
        {"казахстан", "Asia/Almaty"},
        {"актау", "Asia/Aqtau"},
        {"актобе", "Asia/Aqtobe"},
        {"атырау", "Asia/Atyrau"},
        {"костанай", "Asia/Qostanay"},
        {"караганда", "Asia/Almaty"},
        {"лондон", "Europe/London"},
        {"англия", "Europe/London"},
        {"uk", "Europe/London"},
        {"париж", "Europe/Paris"},
        {"франция", "Europe/Paris"},
        {"берлин", "Europe/Berlin"},
        {"германия", "Europe/Berlin"},
        {"варшава", "Europe/Warsaw"},
        {"польша", "Europe/Warsaw"},
        {"прага", "Europe/Prague"},
        {"чехия", "Europe/Prague"},
        {"рим", "Europe/Rome"},
        {"италия", "Europe/Rome"},
        {"мадрид", "Europe/Madrid"},
        {"испания", "Europe/Madrid"},
        {"амстердам", "Europe/Amsterdam"},
        {"стамбул", "Europe/Istanbul"},
        {"турция", "Europe/Istanbul"},
        {"хельсинки", "Europe/Helsinki"},
        {"финляндия", "Europe/Helsinki"},
        {"стокгольм", "Europe/Stockholm"},
        {"швеция", "Europe/Stockholm"},
        {"дубай", "Asia/Dubai"},
        {"оаэ", "Asia/Dubai"},
        {"токио", "Asia/Tokyo"},
        {"япония", "Asia/Tokyo"},
        {"сеул", "Asia/Seoul"},
        {"корея", "Asia/Seoul"},
        {"пекин", "Asia/Shanghai"},
        {"шанхай", "Asia/Shanghai"},
        {"китай", "Asia/Shanghai"},
        {"гонконг", "Asia/Hong_Kong"},
        {"сингапур", "Asia/Singapore"},
        {"бангкок", "Asia/Bangkok"},
        {"таиланд", "Asia/Bangkok"},
        {"джакарта", "Asia/Jakarta"},
        {"индонезия", "Asia/Jakarta"},
        {"дели", "Asia/Kolkata"},
        {"мумбаи", "Asia/Kolkata"},
        {"индия", "Asia/Kolkata"},
        {"нью-йорк", "America/New_York"},
        {"ny", "America/New_York"},
        {"лос-анджелес", "America/Los_Angeles"},
        {"la", "America/Los_Angeles"},
        {"чикаго", "America/Chicago"},
        {"торонто", "America/Toronto"},
        {"канада", "America/Toronto"},
        {"сидней", "Australia/Sydney"},
        {"австралия", "Australia/Sydney"},
        {"окленд", "Pacific/Auckland"},
        {"новая зеландия", "Pacific/Auckland"},
    };
    return aliases;
}

const std::vector<std::pair<std::string, std::string>>& get_cities() {
    static const std::vector<std::pair<std::string, std::string>> cities = {
        {"Лондон", "Europe/London"},
        {"Варшава", "Europe/Warsaw"},
        {"Киев / Минск", "Europe/Kiev"},
        {"Москва", "Europe/Moscow"},
        {"Тбилиси / Ереван", "Asia/Tbilisi"},
        {"Баку", "Asia/Baku"},
        {"Ташкент / Астана", "Asia/Tashkent"},
        {"Актау / Нукус", "Asia/Aqtau"},
        {"Новосибирск", "Asia/Novosibirsk"},
        {"Владивосток", "Asia/Vladivostok"},
    };
    return cities;
}
